### DISCUSSION TITLE
how to integrate into k8s

### DISCUSSION THREAD

**Discussion by melbruki** [jsuto/piler#220] [General]
hello is it possible to deploy mailpiler in k8s?

**Comment by jsuto** [comment]
Well, I haven't tried it yet, but it should work, because piler and all its dependencies can run in containers. See https://github.com/jsuto/piler/blob/master/docker/docker-compose.yaml for more.

One caveat, though. You need to put the following files to /etc/piler dir:

-rw------- 1 piler piler  113 Dec 20 16:05 .my.cnf
-rw-r--r-- 1 root  root     0 Dec 20 16:03 MANTICORE
-rw-r--r-- 1 root  root  1555 Dec 20 16:05 config-site.php
-rw-r--r-- 1 root  root  2346 Dec 20 16:05 piler-nginx.conf
-rw------- 1 piler piler 1355 Dec 20 16:05 piler.conf
-rw------- 1 piler piler   56 Dec 20 16:05 piler.key
-rw------- 1 piler piler 5272 Dec 20 16:05 piler.pem

All these could come from configmaps, except piler.key which is a binary file that's generated with ```dd if=/dev/urandom bs=56 count=1 of=piler.key``` and must not change afterwards.

Let me know, how it goes.

**Comment by melbruki** [comment]
hello so I gave it a try, Im not sure if this was the right move  but I let the startup.sh script create all of those files you mentioned . All the pods came up and I didnt get any error messages. however when I tried to login to the gui, I got an error 504 timeout.  I was able to navigate on the web browser to /ok.txt located in /var/pilar/www . however when i go to index.php it times out. So I think something is wrong with my setup. also i was able to verify connection from the piler pod to manticore and also to mysql. this is the log messages from the piler pod
```
DEBUG: Generating piler.key
DEBUG: Making an ssl certificate
DEBUG: Writing /etc/piler/piler-nginx.conf
DEBUG: Writing /etc/piler/piler.conf
DEBUG: Writing /etc/piler/config-site.php
ERROR 2002 (HY000): Can't connect to server on 'mysql' (115)
DEBUG: mysql is not ready
Database
information_schema
piler
DEBUG: mysql is ready
DEBUG: no metadata table, creating tables
 * Starting periodic command scheduler cron
   ...done.
 * Starting nginx nginx
   ...done.
rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
rsyslogd: activation of module imklog failed [v8.2312.0 try https://www.rsyslog.com/e/2145 ]
starting piler-smtp . . . 
starting piler . .
```


here is my /etc/piler

root@piler-7cbd47f5bc-7kfmz:/etc/piler# ls -l
total 76
-rw-r--r-- 1 root  ubuntu     0 Jan  3 03:25 MANTICORE
-rw-r--r-- 1 root  ubuntu   428 Jan  3 03:25 config-site.dist.php
-rw-r--r-- 1 root  ubuntu   978 Jan  3 03:25 config-site.php
drwxrws--- 2 root  ubuntu 16384 Jan  3 03:25 lost+found
-rwxr-xr-x 1 root  ubuntu  8492 Jan  3 03:25 manticore.conf
-rwxr-xr-x 1 root  ubuntu  8525 Jan  3 03:25 manticore.conf.dist
-rw-r--r-- 1 root  ubuntu  2358 Jan  3 03:25 piler-nginx.conf
-rw-r--r-- 1 root  ubuntu  2343 Jan  3 03:25 piler-nginx.conf.dist
-rw------- 1 piler piler   1367 Jan  3 03:25 piler.conf
-rw-r----- 1 root  ubuntu  1380 Jan  3 03:25 piler.conf.dist
-rw------- 1 piler piler     56 Jan  3 03:25 piler.key
-rw------- 1 piler piler   5272 Jan  3 03:25 piler.pem 

here is my deployment .yaml file 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: piler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piler-etc
  namespace: piler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piler-manticore
  namespace: piler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piler-store
  namespace: piler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: piler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mariadb:11.6.2
        env:
        - name: MYSQL_DATABASE
          value: piler
        - name: MYSQL_USER
          value: piler
        - name: MYSQL_PASSWORD
          value: piler123
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manticore
  namespace: piler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manticore
  template:
    metadata:
      labels:
        app: manticore
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: manticore
        image: manticoresearch/manticore:6.3.8
        volumeMounts:
        - mountPath: /var/lib/manticore
          name: piler-manticore
      volumes:
      - name: piler-manticore
        persistentVolumeClaim:
          claimName: piler-manticore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piler
  namespace: piler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piler
  template:
    metadata:
      labels:
        app: piler
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: piler
        image: sutoj/piler:1.4.7
        command:
          - /start.sh
        env:
        - name: PILER_HOSTNAME
          value: "mailarchive.example.com"
        - name: MYSQL_HOSTNAME
          value: "mysql"
        - name: MANTICORE_HOSTNAME
          value: "manticore"
        - name: MEMCACHED_HOSTNAME
          value: "memcached"
        - name: MYSQL_DATABASE
          value: "piler"
        - name: MYSQL_USER
          value: "piler"
        - name: MYSQL_PASSWORD
          value: "piler123"
        - name: RT
          value: "1"
        volumeMounts:
        - mountPath: /etc/piler
          name: piler-etc
        - mountPath: /var/piler/store
          name: piler-store
      volumes:
      - name: piler-etc
        persistentVolumeClaim:
          claimName: piler-etc
      - name: piler-store
        persistentVolumeClaim:
          claimName: piler-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: piler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: piler
spec:
  ports:
  - port: 3306
    name: mysql
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: manticore
  namespace: piler
spec:
  ports:
  - port: 9306
    name: manticore
  selector:
    app: manticore
---
apiVersion: v1
kind: Service
metadata:
  name: piler
  namespace: piler
spec:
  ports:
  - port: 25
    targetPort: 25
    name: smtp
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: piler
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: piler
spec:
  ports:
  - port: 11211
    name: memcached
  selector:
    app: memcached
```

**Comment by jsuto** [comment]
Impressive so far. So you can get /ok.txt, but not index.php. Check the nginx error log for clues what might be wrong. Also check that the piler processes (piler and piler-smtp) are running, and you can reach the pod on port 25.

**Comment by melbruki** [comment]
finally got it working, :) 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: piler-mysql-config
  namespace: example
data:
  piler.cnf: |
    [mariadb]
    innodb_buffer_pool_size = 256M
    innodb_flush_log_at_trx_commit=1
    innodb_log_buffer_size=64M
    innodb_log_file_size=64M
    innodb_read_io_threads=4
    innodb_write_io_threads=4
    innodb_log_files_in_group=2
    innodb_file_per_table

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manticore-config
  namespace: example
data:
  manticore.conf: |
    index piler1
    {
        type = rt
        path = /var/lib/manticore/piler1
        rt_mem_limit = 512M
        stored_fields =
        min_word_len = 1
        min_prefix_len = 5
        rt_field = sender
        rt_field = rcpt
        rt_field = senderdomain
        rt_field = rcptdomain
        rt_field = subject
        rt_field = body
        rt_field = attachment_types
        rt_attr_bigint = arrived
        rt_attr_bigint = sent
        rt_attr_uint = size
        rt_attr_uint = direction
        rt_attr_uint = folder
        rt_attr_uint = attachments
    }

    index tag1
    {
        type = rt
        path = /var/lib/manticore/tag1
        rt_mem_limit = 16M
        stored_fields = tag
        min_word_len = 2
        min_prefix_len = 5
        rt_field = tag
        rt_attr_bigint = mid
        rt_attr_uint = uid
    }

    index note1
    {
        type = rt
        path = /var/lib/manticore/note1
        rt_mem_limit = 16M
        stored_fields = note
        min_word_len = 2
        min_prefix_len = 5
        rt_field = note
        rt_attr_bigint = mid
        rt_attr_uint = uid
    }

    index audit1
    {
        type = rt
        path = /var/lib/manticore/audit1
        rt_mem_limit = 16M
        stored_fields = *
        min_word_len = 2
        min_prefix_len = 5
        rt_field = email
        rt_field = ipaddr
        rt_field = description
        rt_attr_bigint = ts
        rt_attr_bigint = meta_id
        rt_attr_uint = action
    }

    searchd
    {
        listen                  = 0.0.0.0:9312
        listen                  = 0.0.0.0:9306:mysql
        listen                  = 0.0.0.0:9307:mysql_readonly
        log                     = /var/lib/manticore/manticore.log
        binlog_max_log_size     = 256M
        binlog_path             = /var/lib/manticore
        binlog_flush            = 2
        query_log               = /var/lib/manticore/query.log
        network_timeout         = 5
        pid_file                = /var/lib/manticore/manticore.pid
        seamless_rotate         = 1
        preopen_tables          = 1
        unlink_old              = 1
        thread_stack            = 512k
        buddy_path              =
        rt_flush_period         = 300
    }

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piler-etc
  namespace: example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piler-manticore
  namespace: example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piler-store
  namespace: example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mariadb:11.6.2
        env:
        - name: MYSQL_DATABASE
          value: "piler"
        - name: MYSQL_USER
          value: "piler"
        - name: MYSQL_PASSWORD
          value: "piler123"
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        volumeMounts:
        - mountPath: /etc/mysql/conf.d/piler.cnf
          name: mysql-config-volume
          subPath: piler.cnf
          readOnly: true
        - mountPath: /var/lib/mysql
          name: db-data
      volumes:
      - name: mysql-config-volume
        configMap:
          name: piler-mysql-config
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manticore
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manticore
  template:
    metadata:
      labels:
        app: manticore
    spec:
      securityContext:
        fsGroup: 1000  # Ensures the group has access to mounted volumes
      containers:
      - name: manticore
        image: manticoresearch/manticore:6.3.8
        securityContext:
          runAsUser: 1000  # Ensures the container runs as a non-root user
          runAsGroup: 1000
        volumeMounts:
        - mountPath: /var/lib/manticore
          name: piler-manticore
        - mountPath: /etc/manticoresearch/manticore.conf
          subPath: manticore.conf  # If using ConfigMap for the configuration
          name: manticore-config
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 512Mi
      volumes:
      - name: piler-manticore
        persistentVolumeClaim:
          claimName: piler-manticore
      - name: manticore-config
        configMap:
          name: manticore-config  # Ensure a ConfigMap with this name exists

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piler
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piler
  template:
    metadata:
      labels:
        app: piler
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: piler
        image: sutoj/piler:1.4.7
        command:
          - /start.sh
        env:
        - name: PILER_HOSTNAME
          value: "mailarchive.example.io"
        - name: MYSQL_HOSTNAME
          value: "mysql"
        - name: MANTICORE_HOSTNAME
          value: "manticore"
        - name: MEMCACHED_HOSTNAME
          value: "memcached"
        - name: MYSQL_DATABASE
          value: "piler"
        - name: MYSQL_USER
          value: "piler"
        - name: MYSQL_PASSWORD
          value: "piler123"
        - name: RT
          value: "1"
        volumeMounts:
        - mountPath: /etc/piler
          name: piler-etc
        - mountPath: /var/piler/store
          name: piler-store
        livenessProbe:
          exec:
            command:
            - curl
            - -s
            - smtp://localhost/
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - curl
            - -s
            - smtp://localhost/
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: piler-etc
        persistentVolumeClaim:
          claimName: piler-etc
      - name: piler-store
        persistentVolumeClaim:
          claimName: piler-store

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: example
spec:
  ports:
  - port: 3306
    name: mysql
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: manticore
  namespace: example
spec:
  ports:
  - port: 9306
    name: manticore
    protocol: TCP
    targetPort: 9306
  - port: 9307
    name: manticore-readonly
    protocol: TCP
    targetPort: 9307
  selector:
    app: manticore

---
apiVersion: v1
kind: Service
metadata:
  name: piler
  namespace: example
spec:
  type: LoadBalancer # or specify node NodePort and port forward port 25 on your router if no public IP on node
  ports:
  - port: 25
    targetPort: 25
    name: smtp
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: piler
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: example
spec:
  ports:
  - port: 11211
    name: memcached
  selector:
    app: memcached



---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: piler-ingress
  namespace: example
  labels:
    id: 82ba70fb-0fbd-47d5-b5b0-c8f4935c9f44
spec:
  ingressClassName: nginx
  rules:
  - host: mailarchive.example.io
    http:
      paths:
      - backend:
          service:
            name: piler
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - mailarchive.example.io
    secretName: example-wildcard






```
