### ISSUE TITLE
[FEATURE] Docker: add custom mariadb cnf

### ISSUE THREAD

**Issue by otbutz** [jsuto/piler#114]
**Describe the feature**

The mariadb container allows to bind custom configuration files: 

![grafik](https://github.com/user-attachments/assets/c681d522-963f-4312-ac2a-14e7f235d9ff)

We could ship a `piler.cnf` with the recommended settings from the [FAQ](https://www.mailpiler.org/faq.html).

```yml
  mysql:
    image: mariadb:11.1.2
    container_name: mysql
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - dac_override
      - setuid
      - setgid
    environment:
      - MYSQL_DATABASE=piler
      - MYSQL_USER=piler
      - MYSQL_PASSWORD=piler123
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./piler.cnf:/etc/mysql/conf.d/piler.cnf:ro
```
