### ISSUE TITLE
[BUG] default docker-compose -  allways reindex needed

### ISSUE THREAD

**Issue by SandraCHC** [jsuto/piler#184]
Hello

I have adopted the Docker-compose (https://github.com/jsuto/piler/blob/master/docker/docker-compose.yaml) in Portainer and created the data structure to obtain persistent data.

My Portainer stack looks like this:
```
services:
  mysql:
    image: mariadb:11
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=piler
      - MARIADB_USER=piler
      - MARIADB_PASSWORD=MyPassword
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - TZ=Europe/Zurich
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Data/Persistent/mariadb/data:/var/lib/mysql
      - /Data/Persistent/mariadb/piler.cnf:/etc/mysql/conf.d/piler.cnf:ro

  manticore:
    image: manticoresearch/manticore:6.3.2
    restart: unless-stopped
    volumes:
      - /Data/Persistent/manticore/manticore.conf:/etc/manticoresearch/manticore.conf
      - /Data/Persistent/manticore/data:/var/lib/manticore

  piler:
    image: sutoj/piler:1.4.6
    init: true
    restart: unless-stopped
    environment:
      - MANTICORE_HOSTNAME=manticore
      - MEMCACHED_HOSTNAME=memcached
      - MYSQL_HOSTNAME=mysql
      - MYSQL_DATABASE=piler
      - MYSQL_USER=piler
      - MYSQL_PASSWORD=MyPassword
      - PILER_HOSTNAME=piler.intern.tld
      - RT=1
    ports:
      - "8024:80"
      - "8025:25"
    volumes:
      - /Data/Persistent/piler/etc:/etc/piler
      - /Data/Persistent/piler/store:/var/piler/store
    healthcheck:
      test: curl -s smtp://localhost/
      interval: "20s"
      timeout: "3s"
      start_period: "15s"
      retries: 3
    depends_on:
      - "mysql"
      - "memcached"
      - "manticore"

  memcached:
    image: memcached
    command: -m 64
    restart: unless-stopped
```

I have only made one change in my manticore.conf:
```
index piler1
{
    ....
    charset_table = non_cjk, U+00E4, U+00C4->U+00E4, U+00F6, U+00D6->U+00F6, U+00FC, U+00DC->U+00FC, U+00DF, U+1E9E->U+00DF
    
    ....
```

As soon as I stop and restart the stack, no more emails are displayed and I have to start the reindex with the following command
```
cd /tmp && /usr/bin/reindex -a
```

I found this issue (https://github.com/jsuto/piler/issues/179), but I don't see if it's really the same problem.
I also checked if I have data in the folder /Data/Persistent/manticore/data, which is the case:
```
audit1.lock
audit1.meta
audit1.ram
binlog.001
binlog.lock
binlog.meta
manticore.log
manticore.pid
note1.lock
note1.meta
note1.ram
piler1.lock
piler1.meta
piler1.ram
query.log
tag1.lock
tag1.meta
tag1.ram
```
