### ISSUE TITLE
Upgrade from 1.4.4 to 1.4.5 failed to run

### ISSUE THREAD

**Issue by dwong33** [jsuto/piler#21]
I tried to update my piler, from 1.4.4 to 1.4.5 through updating the docker.

But I cannot run piler after the update, it will show an error like this:

`Error: SQLSTATE[HY000] [2002] Connection refused on database: sphinx`

My docker compose is like this:

```
version: '3.3'
services:
    piler:
        container_name: piler
        network_mode: network
        environment:
            - TZ=America/New_York
            - HOST_OS=Unraid
            - HOST_HOSTNAME=myhost
            - HOST_CONTAINERNAME=piler
            - PILER_HOSTNAME=example.com
            - MYSQL_HOSTNAME=mariadb
            - MYSQL_USER=pileruser
            - MYSQL_PASSWORD=pileruser
            - MYSQL_DATABASE=pilerdb
            - RT=1
        labels:
            - net.unraid.docker.managed=dockerman
            - 'net.unraid.docker.icon=https://i.ibb.co/M7V1LtZ/logo-header.png'
        ports:
            - '380:80/tcp'
            - '3443:443/tcp'
            - '325:25/tcp'
        volumes:
            - '/mnt/user/backup/emailbackup:/var/piler/store:rw'
            - '/mnt/user/appdata/piler/etc/:/etc/piler/:rw'
            - '/mnt/user/appdata/piler/manticore/:/var/piler/manticore/:rw'
        image: 'sutoj/piler:1.4.5'
```

If I move back to 1.4.4, piler runs as usual, no problem. Any insight for that? Thank you
